//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Retrolink
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contracts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contracts()
        {
            this.InstalledEquipment = new HashSet<InstalledEquipment>();
            this.ProvidedServices = new HashSet<ProvidedServices>();
        }
    
        public int ContractID { get; set; }
        public int CustomerID { get; set; }
        public int TariffID { get; set; }
        public System.DateTime ContractDate { get; set; }
        public Nullable<System.DateTime> InstallationDate { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual Tariffs Tariffs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InstalledEquipment> InstalledEquipment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProvidedServices> ProvidedServices { get; set; }
    }
}
