//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Retrolink
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstalledEquipment
    {
        public int InstalledEquipmentID { get; set; }
        public int ContractID { get; set; }
        public int EquipmentID { get; set; }
        public System.DateTime InstallationDate { get; set; }
    
        public virtual Contracts Contracts { get; set; }
        public virtual Equipment Equipment { get; set; }
    }
}
