//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Retrolink
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProvidedServices
    {
        public int ProvidedServiceID { get; set; }
        public int ContractID { get; set; }
        public int ServiceID { get; set; }
        public int EmployeeID { get; set; }
        public Nullable<System.DateTime> ProvideDate { get; set; }
    
        public virtual Contracts Contracts { get; set; }
        public virtual Employees Employees { get; set; }
        public virtual Services Services { get; set; }
    }
}
