//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Retrolink
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupportTickets
    {
        public int TicketID { get; set; }
        public int CustomerID { get; set; }
        public System.DateTime TicketDate { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
    
        public virtual Customers Customers { get; set; }
    }
}
